---
# tasks file for ocp4 e2e
- name: Install required packages
  package:
    name:
      - git
    state: latest

- name: install the 'Development tools' package group
  package: name="@Development tools" state=latest
  when:  ansible_distribution == 'CentOS' or
         ansible_distribution == 'RedHat' or
         ansible_distribution == 'Fedora'

- name: install the 'Build Essential' package group
  package: name="build-essential" state=latest
  when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'

- name: Set test and results directory path
  set_fact:
    test_dir: "{{ e2e_tests_dir }}/src/github.com/openshift"
    results_dir: "{{ ansible_env.HOME }}/e2e_tests_results"
    bin_path: "{{ e2e_tests_dir }}/src/github.com/openshift/origin/openshift-tests"
    repository_command: ""

- name: Set repository command -{4.7, 4.8, 4.9, 4.10}
  set_fact:
    repository_command: "--from-repository quay.io/multi-arch/community-e2e-images"
  when: e2e_tests_git_branch == "release-4.7" or e2e_tests_git_branch == "release-4.8" or e2e_tests_git_branch == "release-4.9" or e2e_tests_git_branch == "release-4.10"

- name: Create test directory
  file:
    path: "{{ test_dir }}"
    state: "{{ item }}"
    mode: '0755'
  with_items:
  - absent
  - directory

- name: Remove existing directory
  file:
    path: "/usr/local/go"
    state: absent

- name: Download and untar golang
  unarchive:
    src: "{{ golang_tarball }}"
    dest: "/usr/local/"
    remote_src: yes

- name: Clone e2e tests repo
  git:
    repo: "{{ e2e_tests_git }}"
    dest: "{{ test_dir }}/origin"
    version: "{{ e2e_tests_git_branch }}"

- name: Copy invert_excluded python script
  template:
    src: ../files/invert_excluded.py
    dest: "{{ test_dir }}/origin/invert_excluded.py"
    mode: '0755'

- name: Add text for running in debian based OS
  shell:
    chdir: "{{ test_dir }}/origin"
    cmd: sed -i '1s/^/SHELL := \/bin\/bash \n/' Makefile && sed -i '1s/^/#!\/usr\/bin\/python3 \n/' invert_excluded.py
  when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'

- name: Run make target
  make:
    chdir: "{{ test_dir }}/origin"
    target: WHAT=cmd/openshift-tests
  environment: "{{ e2e_env }}"

- name: Copy openshift-tests binary
  copy:
   src: "{{ bin_path }}"
   remote_src: true
   dest: "/usr/local/bin/"
   mode: '0755'

- name: Copy kube test repo list
  template:
    src: ../files/kube-test-repo-list
    dest: /tmp/kube-test-repo-list
    mode: '0755'

- name: Download exclude e2e tests list file
  when: e2e_tests_exclude_list_url != "" and github_token != ""
  get_url:
    url: "{{ e2e_tests_exclude_list_url }}"
    dest: "{{ test_dir }}/origin/excluded_tests"
    headers:
      Authorization: "token {{ github_token }}"
      Accept: application/vnd.github.v3.raw

- name: Create exclude e2e tests list
  when: e2e_tests_exclude_list_url == ""
  file:
    path: "{{ test_dir }}/origin/excluded_tests"
    state: touch
    mode: u=rw,g=r,o=r

- name: Create results directory
  file:
    path: "{{ results_dir }}"
    state: "{{ item }}"
    mode: '0755'
  with_items:
  - absent
  - directory

# Check Nodes status
- name: Check all nodes are Ready
  shell: oc wait --all --for=condition=Ready nodes --timeout=300s

# Check CO status
- name: Check if all co are in AVAILABLE state and check no any co are in PROGRESSING state and DEGRADED state
  shell: oc get co -n default --no-headers | awk '{ print $3 $4 $5 }' | grep -w -v TrueFalseFalse | wc -l
  register: co_status
  until: co_status.stdout|int == 0
  retries: 30
  delay: 120
  ignore_errors: yes

- name: Fail if Cluster operators are not in good status
  fail:
    msg: "Cluster operators are not in good status. Skipping E2E tests !!"
  when: 0 != co_status.stdout|int

# Check PODS
- name: Verify all PODS are Running or Completed
  shell: oc get pods -A | awk 'NR>1 {if($4!="Running" && $4!="Completed" ){print $2" "$4}}'
  register: pods_status
  until: pods_status.stdout|length == 0
  retries: 30
  delay: 60
  ignore_errors: yes

- debug:
    msg: "Unhealthy PODS: {{ pods_status.stdout_lines }}"
  when: 0 != pods_status.stdout|length

# Running E2E
- name: Prepare test suites and run e2e tests
  shell: |
    openshift-tests run openshift/conformance/parallel --dry-run | ./invert_excluded.py excluded_tests > test-suite.txt
    openshift-tests run -f ./test-suite.txt {{ repository_command }} -o {{ results_dir }}/conformance-parallel-out-0.txt --junit-dir {{ results_dir }}/conformance-parallel > /dev/null
    sed -e 's/\"/\\"/g;s/.*/\"&\"/'  {{ results_dir }}/conformance-parallel-out-0.txt   | awk '/Failing tests:/,EOF' | tail -n +3 | head -n -4 > {{ results_dir }}/failed-e2e-results.txt
  args:
    chdir: "{{ test_dir }}/origin"
  environment: "{{ e2e_env }}"
  register: opp
  when: e2e_tests_enabled and co_status.stdout|int == 0

# Re-Running E2E
- name: Re run e2e failed tests
  shell: |
    cnt=0
    IFS=' ' read -ra ADDR1 <<< $(cat {{ results_dir }}/conformance-parallel-out-0.txt | grep 'pass\|fail\|skip' | tail -1)
    if  [ "0" -ne "$(wc -l < "{{ results_dir }}/failed-e2e-results.txt")" ]
    then
      # Storing start time
      START_TIME=$(date +%s);

      # Storing the hours, minutes and seconds of the first e2e execution
      IFS="hm" read -d '' hr min sec<<< $(echo ${ADDR1[7]} | sed -e 's/[()s]//g')

      while [ $cnt -lt 5 ]
      do
        f_test="$(wc -l < "{{ results_dir }}/failed-e2e-results.txt")"
        cnt=$(( $cnt + 1 ))
        openshift-tests run -f {{ results_dir }}/failed-e2e-results.txt {{ repository_command }} -o {{ results_dir }}/conformance-parallel-out-${cnt}.txt --junit-dir {{ results_dir }}/conformance-parallel > /dev/null
        sed -e 's/\"/\\"/g;s/.*/\"&\"/' "{{ results_dir }}/conformance-parallel-out-${cnt}.txt" | awk '/Failing tests:/,EOF' | tail -n +3 | head -n -4 > {{ results_dir }}/failed-e2e-results.txt
        awk -i inplace '/\S/' "{{ results_dir }}/failed-e2e-results.txt"

        IFS=' ' read -ra ADDR2 <<< $(cat {{ results_dir }}/conformance-parallel-out-${cnt}.txt | grep 'pass\|fail\|skip' | tail -1)
        # Calculating the passed and skipped test cases
        if [ ${{ "{" }}{{ "#" }}ADDR2[@]} -eq "5" ]
        then
          ADDR1[3]=$((${ADDR2[0]} + ${ADDR1[3]}))
          ADDR1[5]=$((${ADDR2[2]} + ${ADDR1[5]}))
          ADDR2[1]=0
        else
          ADDR1[3]=$((${ADDR2[3]} + ${ADDR1[3]}))
          ADDR1[5]=$((${ADDR2[5]} + ${ADDR1[5]}))
        fi

        # exiting the loop if no new test passes
        if [ "0" -eq "$(wc -l < "{{ results_dir }}/failed-e2e-results.txt")" ] || [ $f_test -eq "$(wc -l < "{{ results_dir }}/failed-e2e-results.txt")" ]
        then
            break
        fi
      done

      # Calculating time required for e2e execution
      END_TIME=$(date +%s);
      diff=$(($sec + END_TIME - START_TIME))
      hrs=$(($hr + ($min + $diff/60)/60))
      mins=$((($min + $diff/60)%60))
      secs=$(($diff%60))
      e2e_time="(${hrs}h${mins}m${secs}s)"

      mv {{ results_dir }}/conformance-parallel-out-${cnt}.txt {{ results_dir }}/conformance-parallel-out.txt
      echo " ${ADDR2[1]} fail, ${ADDR1[3]} pass, ${ADDR1[5]} skip $e2e_time" >  {{ results_dir }}/summary.txt
    else
       mv {{ results_dir }}/conformance-parallel-out-0.txt {{ results_dir }}/conformance-parallel-out.txt
       summary=$(cat {{ results_dir }}/conformance-parallel-out.txt | grep 'pass\|fail\|skip' | tail -1)
       sed -e 's/\"/\\"/g;s/.*/\"&\"/'  {{ results_dir }}/conformance-parallel-out.txt   | awk '/Failing tests:/,EOF' | tail -n +3 | head -n -4 > {{ results_dir }}/failed-e2e-results.txt
       echo $summary |sed 's/error://' >> {{ results_dir }}/summary.txt
    fi
  args:
    chdir: "{{ test_dir }}/origin"
    executable: /bin/bash
  environment: "{{ e2e_env }}"
  register: op
  when: e2e_tests_enabled and co_status.stdout|int == 0
  ignore_errors: yes

