---

coo_operator_deploy: true
coo_cleanup: true
coo_role_enable: false
coo_namespace: openshift-observability-operator
coo_catalogsource_name: coo-catalog 
coo_catalogsource_image: brew.registry.redhat.io/rh-osbs/iib:760399
coo_channel: development
