---
- import_playbook: ocp-scale.yml
  when: scale_test_enabled

- import_playbook: ocp-registry.yml
  when: expose_image_registry

- import_playbook: ocp-alerts.yml
  when: ocp_alerts

- import_playbook: ocp-e2e.yml
  when: e2e_tests_enabled or e2e_upgrade_image != ""

- import_playbook: ocp-ovnkube-cni.yml
  when: ocp_ovnkube_cni

- import_playbook: ocp-migration.yml
  when: ocp_migration

- import_playbook: global-secret-update.yml
  when: global_secret_update

- import_playbook: ocp-cluster-logging.yml
  when: ocp_cluster_logging

- import_playbook: ocp-etcd-encryption-decryption.yml
  when: ocp_etcd

- import_playbook: ocp-ibm-block-csi.yml
  when: ocp_ibm_block_csi

- import_playbook: ocp-nfd-operator.yml
  when: ocp_nfd

- import_playbook: golang-installation.yml
  when: golang_installation
  
- import_playbook: ocp-service-binding-operator.yml
  when: ocp_sbo 
  
- import_playbook: ocp-htpasswd-identity-provider.yml
  when: htpasswd_identity_provider

- import_playbook: ocp-hpa.yml
  when: ocp_hpa

- import_playbook: ocp-jenkins.yml
  when: ocp_jenkins

- import_playbook: ocp-vpa-operator.yml
  when: ocp_vpa

- import_playbook: ocp-hostpath.yml
  when: ocp_hostpath_enabled

- import_playbook: ocp-csi-driver.yml
  when: ocp_csi_driver

- import_playbook: ocp-iscsi.yml
  when: ocp_iSCSI_enabled

- import_playbook: ocp-cli-plugins.yml
  when: enable_cli_plugins_test is defined and enable_cli_plugins_test

- import_playbook: ocp-sso.yml
  when: sso_enabled is defined and sso_enabled

- import_playbook: ocp-compliance.yml
  when: compliance_enabled is defined and compliance_enabled

- import_playbook: hypershift.yml
  when: >
        (hypershift_install is defined and hypershift_install) or 
        (hypershift_destroy is defined and hypershift_destroy)

- import_playbook: ocp-fio.yaml
  when: fio_enabled is defined and fio_enabled

- import_playbook: ipa-identity-provider.yml
  when: ipa_identity_provider is defined and ipa_identity_provider

- import_playbook: monitoring-user-defined-projects.yml
  when: enable_user_defined_project_monitoring is defined and enable_user_defined_project_monitoring

- import_playbook: request-header-identity-provider.yml
  when: request_header_provider is defined and request_header_provider

- import_playbook: ocp-descheduler.yml
  when: descheduler_role_enable is defined and descheduler_role_enable

- import_playbook: ocp-verification-tests.yml
  when: verification_enabled is defined and verification_enabled

- import_playbook: ocp-sctp.yml
  when: sctp_enabled is defined and sctp_enabled
  
- import_playbook: ocp-pod-disruption-budget.yml
  when: pdb_enabled is defined and pdb_enabled

- import_playbook: ocp-nmstate-operator.yml
  when: nmstate_enabled is defined and nmstate_enabled

- import_playbook: ocp-scheduler.yml
  when: scheduler_role_enable is defined and scheduler_role_enable

- import_playbook: cro.yml
  when: cro_role_enable is defined and cro_role_enable

- import_playbook: ocp-metallb-operator.yml
  when: metallb_enabled is defined and metallb_enabled

- import_playbook: ocp-network-observability.yml
  when: noo_role_enable is defined and noo_role_enable

- import_playbook: ocp-coo.yml
  when: coo_role_enable is defined and coo_role_enable

- import_playbook: ocp-etcd-rotate-encryption-key.yml
  when: ocp_etcd_key_rotation_enable is defined and ocp_etcd_key_rotation_enable

- import_playbook: ocp-logging-tests-private-e2e.yml
  when: ocp_logging_tests_private_e2e_enabled is defined and ocp_logging_tests_private_e2e_enabled

- import_playbook: hypershift-agent.yml
  when: >
        (hypershift_agent_install is defined and hypershift_agent_install) or
        (hypershift_agent_destroy is defined and hypershift_agent_destroy)
  
- import_playbook: ocp-lso.yml
  when: lso_enabled is defined and lso_enabled

- import_playbook: ocp-operator-api.yml
  when: op_api_role_enable is defined and op_api_role_enable

- import_playbook: ocp-cluster-etcd-operator.yml
  when: cluster_etcd_enabled is defined and cluster_etcd_enabled

- import_playbook: ocp-kube-burner.yml
  when: enable_kube_burner is defined and enable_kube_burner
  
- import_playbook: scheduler-plugins.yml
  when: ocp_scheduler_plugins_enable is defined and ocp_scheduler_plugins_enable  

- import_playbook: ocp-ingress-firewall-operator.yml
  when: ingress_firewall_enabled is defined and ingress_firewall_enabled

- import_playbook: ocp-cpu-manager.yml
  when: validate_cpum is defined and validate_cpum
